configured_endpoints: 54
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/snag%2Fsnag-solutions-42a1ce88ba686abb34ed82fadcd23dd72767d3bbcf0ee9fe17efd76ebd013246.yml
openapi_spec_hash: 78c1d874da4cfe5420f61b0cb3f9f26f
config_hash: f528c5dfc889d4c6e4d41a850d1adc80
