configured_endpoints: 52
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/snag%2Fsnag-solutions-428f74e2fbeaed30fe8aa7aefb9eb59da95884ba59138503cb1f9fee8e6bffac.yml
openapi_spec_hash: 2263673fe51ef440e3f7b2550b2bafe8
config_hash: 0f44fad05641d656c8a24cd042ece83f
