configured_endpoints: 82
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/snag%2Fsnag-solutions-af6a80da670f4a3dcbe6cc2da54a59ad5f6585266db74039ebeaa58e733171a7.yml
openapi_spec_hash: 6f3656a8cedcae8fabb5cec65a388c02
config_hash: 6eb83a5d7dd1fa0136c6d6d63bf7fc3e
