configured_endpoints: 66
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/snag%2Fsnag-solutions-dbfb734d04eacf9baefcbe3d2b0abe2c05ee9a51075f9686038e5f997ca8de08.yml
openapi_spec_hash: e76d5adf159b0dc1eae8a97cea1d17ea
config_hash: 97e9c6f4e087b5a89855a49fbe442e82
